--create user lab identified by lab
--grant create any table to lab
--grant alter any table to lab
--grant drop any table to lab
--grant connect to lab
--grant drop any trigger to lab
--grant create any trigger to lab
--grant insert any table to lab;
--GRANT UNLIMITED TABLESPACE TO lab; 
--grant DEBUG CONNECT SESSION to lab;
--grant  DEBUG ANY PROCEDURE to lab;
--grant create any procedure to lab
--grant create any sequence to lab;
--grant create any type to lab;